# Numpy Tutorial 

In [5]:
import numpy as np

In [6]:
myarray = np.array([[1,2,4,5]],np.int8)  # int8 -> its store 8 bytes of integer data 

In [7]:
myarray 

array([[1, 2, 4, 5]], dtype=int8)

In [8]:
print(type(myarray))

<class 'numpy.ndarray'>


In [9]:
myarray[0,1]

2

In [10]:
myarray.shape  # shape ->define the structure of the array  output say 1 row and 4 columns

(1, 4)

In [11]:
myarray[0,1]=7

In [12]:
myarray

array([[1, 7, 4, 5]], dtype=int8)

# Array Creation : Conversion from other python data structure

In [14]:
import numpy as np

In [15]:
listarray=np.array([[12,23,4],[2,8,9],[92,54,24]])

In [16]:
listarray

array([[12, 23,  4],
       [ 2,  8,  9],
       [92, 54, 24]])

In [17]:
listarray.dtype

dtype('int32')

In [18]:
listarray.shape

(3, 3)

In [20]:
listarray.size  #size -> it will print all the element of the array

9

In [21]:
np.array({34,78})

array({34, 78}, dtype=object)

# Array Creation : Intrinsic Numpy array creation objects

In [22]:
import numpy as np

In [23]:
zeros=np.zeros((2,5))

In [24]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [25]:
 rng=np.arange(15)  #arange->It print range betwen nos

In [26]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [27]:
lspace=np.linspace(1,20,3)

In [28]:
lspace

array([ 1. , 10.5, 20. ])

In [30]:
emp=np.empty((4,6))

In [31]:
emp

array([[6.23042070e-307, 1.42417221e-306, 1.60219306e-306,
        7.56593017e-307, 7.56587584e-307, 1.37961302e-306],
       [1.05699242e-307, 8.01097889e-307, 1.78020169e-306,
        7.56601165e-307, 1.02359984e-306, 1.42417221e-306],
       [1.42419530e-306, 1.37962456e-306, 1.11260959e-306,
        9.34603679e-307, 1.11260348e-306, 1.33511562e-306],
       [1.11260348e-306, 1.33511562e-306, 8.45590539e-307,
        1.24611741e-306, 1.37961709e-306, 2.22522596e-306]])

In [32]:
emp_like=np.empty_like(lspace)

In [33]:
emp_like

array([7.74860419e-304, 7.74860419e-304, 7.74860419e-304])

In [34]:
ide=np.identity(20)

In [35]:
ide

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.

In [36]:
ide.shape

(20, 20)

In [37]:
arr=np.arange(99)

In [38]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [40]:
arr=arr.reshape(3,33)

In [41]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [44]:
arr=arr.ravel()

In [45]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [48]:
arr.shape

(99,)

In [49]:
x=[[1,2,3],[4,5,6],[7,1,0]]

In [50]:
ar=np.array(x)

In [51]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [52]:
ar.sum(axis=0)

array([12,  8,  9])

In [53]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [54]:
ar.T # transpose matrix

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [55]:
ar.flat

In [56]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [57]:
ar.ndim # 2 dimensional

2

In [58]:
ar.size

9

In [59]:
ar.nbytes

36

In [60]:
one=np.array([1,2,3,5])

In [61]:
one.argmax() # it return the index value of max elements

3

In [62]:
one.argmin()  # it return the index value of min elements

0

In [63]:
one.argsort()

array([0, 1, 2, 3], dtype=int64)

In [64]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [65]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [66]:
ar.argmin()

8

In [67]:
ar.argmax()

6

In [68]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [69]:
ar.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [70]:
ar.argmin(axis=0)

array([0, 2, 2], dtype=int64)

In [71]:
ar.argmin(axis=1)

array([0, 0, 2], dtype=int64)

In [72]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [74]:
ar.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [75]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [76]:
ar2=np.array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [77]:
ar2

array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [79]:
ar_sum=ar + ar2

In [80]:
ar_sum

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [81]:
ar_multipli=ar * ar2

In [82]:
ar_multipli

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [83]:
ar_sub=ar - ar2

In [84]:
ar_sub

array([[ 0,  0,  2],
       [ 0,  5,  0],
       [-1,  0,  0]])

In [85]:
ar_div=ar / ar2

<ipython-input-85-2580b5252796>:1: RuntimeWarning: divide by zero encountered in divide
  ar_div=ar / ar2
<ipython-input-85-2580b5252796>:1: RuntimeWarning: invalid value encountered in divide
  ar_div=ar / ar2


In [86]:
ar_div

array([[1.   , 1.   , 3.   ],
       [1.   ,   inf, 1.   ],
       [0.875, 1.   ,   nan]])

In [87]:
ar_squareroot=np.sqrt(ar) # print squareroot of each element of arr

In [88]:
ar_squareroot

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [89]:
ar_sum=ar.sum() # print sum of element in array

In [90]:
ar_sum

29

In [91]:
ar_max=ar.max()  # print max element in array

In [92]:
ar_max

7

In [93]:
ar_min=ar.min()  # print min element in array

In [94]:
ar_min

0

In [95]:
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [96]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [98]:
np.count_nonzero(ar) # its count the non zero element in array

8

In [99]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [100]:
import sys

In [102]:
py_ar=[2,4,56,3]

In [103]:
np_ar=np.array(py_ar)

In [104]:
sys.getsizeof(1)*len(py_ar)

112

In [108]:
np_ar.itemsize * np_ar.size

16